NODE_CON_ADDR           ="#NODE_CONN_ADDR"
MULTI_CONN_ADDR         ="#MULTI_CONN_ADDR"
ASK_RANDOM_NODE         ="#ASK_RANDOM_NODE"


CONNECTABLE_NODES       ="#CONNECTABLE_NODES"
CMD_JOIN_MSG            ="#JOIN_TO_NETWORK"
CMD_DISCONNECT_NETWORK  ="#DISCONNECT"

ASK_NODES_TO_CONNECT    ="#ASK_NODES_TO_CONNECT"


RESPONSE_RANDOM_NODE    ="#RESPONSE_RANDOM_NODE"

GIVE_ALL_NODES          ="#GIVE_ALL_NODES"


STARTUP_CONNECTION      ="#STARTUP_CONNECTION"

STARTUP_DISCONNECT      ="#STARTUP_DISCONNECT"
